# ------------------------------------------------------------------------------------
# 메시지 세팅
# ------------------------------------------------------------------------------------
messages:
  # 접두사
  prefix: '&a[수표] &r'

  # 수표를 사용하였을 때 출력되는 메시지
  useCheque: "수표를 사용하여 &6{money}&f원을 획득하였습니다."

  # 수표를 생성하였을 때 출력되는 메시지
  # {money} : 뽑은 수표의 돈
  createCheque: "&6{money}&f원의 수표를 생성하였습니다."

  # 콘피그를 다시 불러왔을 때 출력되는 메시지
  reloadConfig: "&a콘피그를 리로드하였습니다."

# ------------------------------------------------------------------------------------
# 오류 메세지 세팅
# ------------------------------------------------------------------------------------
errorMessages:

  # 명령어를 실행할 때 권한이 없을 경우 출력되는 메시지
  noPermission: "&c당신은 해당 명령어를 사용할 권한이 없습니다."

  # 콘솔에서 명령어를 사용할 경우 출력되는 메시지
  noConsole: "&c해당 명령어를 콘솔에서 사용할 수 없습니다."

  # 올바르지 않는 명령어를 사용할 경우 출력되는 메시지
  wrongCommand: "&c올바르지 않은 명령어입니다."

  # 숫자로 입력하지 않았을 경우 출력되는 메시지
  noNumber: "&c숫자로 입력해주세요."

  # 수표를 뽑을 때 돈을 입력하지 않았을 경우 출력되는 메시지
  noMoney: "&c돈을 입력해주세요."

  # 수표를 뽑을 때 수표의 양을 입력하지 않았을 경우 출력되는 메시지
  noAmount: "&c뽑을 수표의 양을 입력해주세요."

  # 숫자를 음수로 입력했을 경우 출력되는 메시지
  wrongNumber: "&c숫자는 음수 단위로 표현할 수 없습니다."

  # 뽑으려는 수표의 금액보다 돈이 없을 경우 출력되는 메시지
  enoughMoney: "&c돈이 부족하여 수표를 발급할 수 없습니다."

# ------------------------------------------------------------------------------------
# 수표 세팅
# ------------------------------------------------------------------------------------
cheque:

  # 아이템 종류
  material: PAPER

  # 아이템 이름
  displayname: "&a[수표] &6{money}&f원"

  # 아이템 로어
  lore:
    - ""
    - "&6[!] &f우클릭 시, &6{money}&f원을 지급 받습니다."
    - ""